version: '3'

services:
  app:
    build:
      context: ./build/php
      dockerfile: Dockerfile
    image: php:7.3-fpm
    container_name: app
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - ./src:/var/www
      - ./build/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  server:
    image: nginx:alpine
    container_name: server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www
      - ./build/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:8.0.18
    container_name: db
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./build/mysql/my.cnf:/etc/mysql/my.cnf
    env_file:
      - .env
    networks:
      - app-network

  cron:
    image: mcuadros/ofelia:latest
    container_name: cron
    depends_on:
      - app
    command: daemon --config=/etc/ofelia/config.ini
    volumes:
      - ./build/ofelia/config.ini:/etc/ofelia/config.ini
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
