version: '3'

services:
  node:
    build:
      context: ./src/public/angular
      dockerfile: Dockerfile
    image: node:lts-alpine
    container_name: node
    working_dir: /app
    ports:
    - 4200:4200
    volumes:
      - ./src/public/angular:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
