version: '3'

services:
  app:
    volumes:
      - ./src/backend:/var/www/api

  server:
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./src/backend:/var/www/api
      - ./src/frontend/dist/angular:/var/www/app
      - ./deploy/nginx/conf.d/production:/etc/nginx/conf.d/
