version: '3'

services:
  node:
    build:
      context: ./src/public/angular
      dockerfile: Dockerfile
    image: node:lts-alpine
    container_name: node
    working_dir: /app/app-dir
    ports:
    - 4200:4200
    volumes:
      - ./src/public/angular:/app/app-dir
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
